[package]
name = "grpc-tutorial"
version = "0.1.0"
edition = "2024"

[dependencies]
tonic = "0.6"
prost = "0.10"
tokio = { version = "1", features = ["full"] }
tokio-stream = "0.1"
tonic-build = "0.13.0"

[build-dependencies]
prost-build = "0.10"